//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     生成时间 05/27/2019 13:55:17 By 朱峰
//     对此文件的更改可能会导致不正确的行为，并且如果
//     文件已存在，不会覆盖。
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Project.Model.Conditions
{
    public class AppointmentCondition
    {
        //预约日期
        public DateTime? AppointmentDate { get; set; }
    }
}
