//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     生成时间 05/06/2019 13:27:04 By 朱峰
//     对此文件的更改可能会导致不正确的行为，并且如果
//     文件已存在，不会覆盖。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Model.Conditions
{
    public class EmailConfigCondition
    {
        public string Keyword { get; set; }
    }
}
