//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     生成时间 04/25/2019 17:08:32 By 朱峰
//     对此文件的更改可能会导致不正确的行为，并且如果
//     文件已存在，不会覆盖。
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Project.Model.Conditions
{
    public class WordCondition
    {
        public int Type { get; set; }

        public DateTime? Start { get; set; }

        public DateTime? End { get; set; }

        public string Keyword { get; set; }
    }
}
