//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     生成时间 03/21/2019 08:57:52 By 朱峰
//     对此文件的更改可能会导致不正确的行为，并且如果
//     文件已存在，不会覆盖。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Project.Model;
using Project.Model.Conditions;
using Project.Model.Dtos;

namespace Project.IBLL
{
    public interface IAccountService
    {
        /// <summary>
        /// 新增Account
        /// </summary>
        /// <param name="entity"></param>
        /// <returns></returns>
        int Insert(Account entity);

        /// <summary>
        ///     批量新增Account
        /// </summary>
        /// <param name="entitys"></param>
        /// <returns></returns>
        bool Insert(List<Account> entitys);

        /// <summary>
        /// 更新产品
        /// </summary>
        /// <returns></returns>
        bool Update(Account entity);

        /// <summary>
        /// 批量更新(不使用事务)
        /// </summary>
        /// <param name="entitys"></param>
        /// <returns></returns>
        bool Update(List<Account> entitys);

        /// <summary>
        /// 逻辑删除Account
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        bool SoftDelete(int id);

        /// <summary>
        /// 批量逻辑删除Account(不使用事务)
        /// </summary>
        /// <param name="ids"></param>
        /// <returns></returns>
        bool SoftDelete(List<int> ids);

        /// <summary>
        /// 判断Account是否存在
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        bool Exists(int id);

        /// <summary>
        ///     根据主键获取Account
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        Account GetByPk(int id);

        /// <summary>
        ///     根据主键获取Account集合
        /// </summary>
        /// <param name="ids"></param>
        /// <returns></returns>
        List<Account> GetList(List<int> ids);

        /// <summary>
        ///     分页方法
        /// </summary>
        /// <param name="page"></param>
        /// <param name="size"></param>
        /// <param name="sort"></param>
        /// <param name="condition"></param>
        /// <returns></returns>
        PageModel<Account> GetByPage(int page, int size, string sort, AccountCondition condition);

        /// <summary>
        /// 判断LoginName是否存在
        /// </summary>
        /// <param name="loginName"></param>
        /// <param name="id"></param>
        /// <returns></returns>
        bool ExistLoginName(string loginName, int? id);

        /// <summary>
        /// 根据loginName和password获取账号
        /// </summary>
        /// <param name="loginName"></param>
        /// <param name="password"></param>
        /// <param name="id"></param>
        /// <returns></returns>
        Account GetAccount(string loginName, string password);
    }
}
