//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     生成时间 05/23/2019 10:37:27 By 朱峰
//     对此文件的更改可能会导致不正确的行为，并且如果
//     文件已存在，不会覆盖。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Project.Model;
using Project.Model.Conditions;
using Project.Model.Dtos;

namespace Project.IBLL
{
    public interface IAchievementService
    {
        /// <summary>
        /// 新增Achievement
        /// </summary>
        /// <param name="entity"></param>
        /// <returns></returns>
        int Insert(Achievement entity);

        /// <summary>
        ///     批量新增Achievement
        /// </summary>
        /// <param name="entitys"></param>
        /// <returns></returns>
        bool Insert(List<Achievement> entitys);

        /// <summary>
        /// 更新产品
        /// </summary>
        /// <returns></returns>
        bool Update(Achievement entity);

        /// <summary>
        /// 批量更新(不使用事务)
        /// </summary>
        /// <param name="entitys"></param>
        /// <returns></returns>
        bool Update(List<Achievement> entitys);

        /// <summary>
        /// 逻辑删除Achievement
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        bool SoftDelete(int id);

        /// <summary>
        /// 批量逻辑删除Achievement(不使用事务)
        /// </summary>
        /// <param name="ids"></param>
        /// <returns></returns>
        bool SoftDelete(List<int> ids);

        /// <summary>
        /// 判断Achievement是否存在
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        bool Exists(int id);

        /// <summary>
        ///     根据主键获取Achievement
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        Achievement GetByPk(int id);

        /// <summary>
        ///     根据主键获取Achievement集合
        /// </summary>
        /// <param name="ids"></param>
        /// <returns></returns>
        List<Achievement> GetList(List<int> ids);

        /// <summary>
        ///     分页方法
        /// </summary>
        /// <param name="page"></param>
        /// <param name="size"></param>
        /// <param name="sort"></param>
        /// <param name="condition"></param>
        /// <returns></returns>
        PageModel<Achievement> GetByPage(int page, int size, string sort, AchievementCondition condition);
    }
}
