//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     生成时间 05/27/2019 13:55:17 By 朱峰
//     对此文件的更改可能会导致不正确的行为，并且如果
//     文件已存在，不会覆盖。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Project.Model;
using Project.Model.Conditions;
using Project.Model.Dtos;

namespace Project.IBLL
{
    public interface IAppointmentService
    {
        /// <summary>
        /// 新增Appointment
        /// </summary>
        /// <param name="entity"></param>
        /// <returns></returns>
        int Insert(Appointment entity);

        /// <summary>
        ///     批量新增Appointment
        /// </summary>
        /// <param name="entitys"></param>
        /// <returns></returns>
        bool Insert(List<Appointment> entitys);

        /// <summary>
        /// 更新产品
        /// </summary>
        /// <returns></returns>
        bool Update(Appointment entity);

        /// <summary>
        /// 批量更新(不使用事务)
        /// </summary>
        /// <param name="entitys"></param>
        /// <returns></returns>
        bool Update(List<Appointment> entitys);

        /// <summary>
        /// 逻辑删除Appointment
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        bool SoftDelete(int id);

        /// <summary>
        /// 批量逻辑删除Appointment(不使用事务)
        /// </summary>
        /// <param name="ids"></param>
        /// <returns></returns>
        bool SoftDelete(List<int> ids);

        /// <summary>
        /// 判断Appointment是否存在
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        bool Exists(int id);

        /// <summary>
        ///     根据主键获取Appointment
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        Appointment GetByPk(int id);

        /// <summary>
        ///     根据主键获取Appointment集合
        /// </summary>
        /// <param name="ids"></param>
        /// <returns></returns>
        List<Appointment> GetList(List<int> ids);

        /// <summary>
        ///     分页方法
        /// </summary>
        /// <param name="page"></param>
        /// <param name="size"></param>
        /// <param name="sort"></param>
        /// <param name="condition"></param>
        /// <returns></returns>
        PageModel<Appointment> GetByPage(int page, int size, string sort, AppointmentCondition condition);

        /// <summary>
        /// 根据预约日期添加数据
        /// </summary>
        /// <param name="AppointmentDate">预约日期</param>
        /// <returns></returns>
        bool AddAppointmentsByDate(DateTime AppointmentDate);
    }
}
