//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     生成时间 05/06/2019 13:27:04 By 朱峰
//     对此文件的更改可能会导致不正确的行为，并且如果
//     文件已存在，不会覆盖。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Project.Model;
using Project.Model.Conditions;
using Project.Model.Dtos;

namespace Project.IBLL
{
    public interface IEmailConfigService
    {
        /// <summary>
        /// 新增EmailConfig
        /// </summary>
        /// <param name="entity"></param>
        /// <returns></returns>
        int Insert(EmailConfig entity);

        /// <summary>
        ///     批量新增EmailConfig
        /// </summary>
        /// <param name="entitys"></param>
        /// <returns></returns>
        bool Insert(List<EmailConfig> entitys);

        /// <summary>
        /// 更新产品
        /// </summary>
        /// <returns></returns>
        bool Update(EmailConfig entity);

        /// <summary>
        /// 批量更新(不使用事务)
        /// </summary>
        /// <param name="entitys"></param>
        /// <returns></returns>
        bool Update(List<EmailConfig> entitys);

        /// <summary>
        /// 逻辑删除EmailConfig
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        bool SoftDelete(int id);

        /// <summary>
        /// 批量逻辑删除EmailConfig(不使用事务)
        /// </summary>
        /// <param name="ids"></param>
        /// <returns></returns>
        bool SoftDelete(List<int> ids);

        /// <summary>
        /// 判断EmailConfig是否存在
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        bool Exists(int id);

        /// <summary>
        ///     根据主键获取EmailConfig
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        EmailConfig GetByPk(int id);

        /// <summary>
        ///     根据主键获取EmailConfig集合
        /// </summary>
        /// <param name="ids"></param>
        /// <returns></returns>
        List<EmailConfig> GetList(List<int> ids);

        /// <summary>
        ///     分页方法
        /// </summary>
        /// <param name="page"></param>
        /// <param name="size"></param>
        /// <param name="sort"></param>
        /// <param name="condition"></param>
        /// <returns></returns>
        PageModel<EmailConfig> GetByPage(int page, int size, string sort, EmailConfigCondition condition);
    }
}
