//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     生成时间 05/06/2019 13:27:04 By 朱峰
//     对此文件的更改可能会导致不正确的行为，并且如果
//     文件已存在，不会覆盖。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Project.Model;
using Project.Model.Conditions;
using Project.Model.Dtos;

namespace Project.IBLL
{
    public interface IFtpConfigService
    {
        /// <summary>
        /// 新增FtpConfig
        /// </summary>
        /// <param name="entity"></param>
        /// <returns></returns>
        int Insert(FtpConfig entity);

        /// <summary>
        ///     批量新增FtpConfig
        /// </summary>
        /// <param name="entitys"></param>
        /// <returns></returns>
        bool Insert(List<FtpConfig> entitys);

        /// <summary>
        /// 更新产品
        /// </summary>
        /// <returns></returns>
        bool Update(FtpConfig entity);

        /// <summary>
        /// 批量更新(不使用事务)
        /// </summary>
        /// <param name="entitys"></param>
        /// <returns></returns>
        bool Update(List<FtpConfig> entitys);

        /// <summary>
        /// 逻辑删除FtpConfig
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        bool SoftDelete(int id);

        /// <summary>
        /// 批量逻辑删除FtpConfig(不使用事务)
        /// </summary>
        /// <param name="ids"></param>
        /// <returns></returns>
        bool SoftDelete(List<int> ids);

        /// <summary>
        /// 判断FtpConfig是否存在
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        bool Exists(int id);

        /// <summary>
        ///     根据主键获取FtpConfig
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        FtpConfig GetByPk(int id);

        /// <summary>
        ///     根据主键获取FtpConfig集合
        /// </summary>
        /// <param name="ids"></param>
        /// <returns></returns>
        List<FtpConfig> GetList(List<int> ids);

        /// <summary>
        ///     分页方法
        /// </summary>
        /// <param name="page"></param>
        /// <param name="size"></param>
        /// <param name="sort"></param>
        /// <param name="condition"></param>
        /// <returns></returns>
        PageModel<FtpConfig> GetByPage(int page, int size, string sort, FtpConfigCondition condition);
    }
}
