//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     生成时间 07/24/2018 16:31:02 By 朱峰
//     对此文件的更改可能会导致不正确的行为，并且如果
//     文件已存在，不会覆盖。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Project.Model;
using Project.Model.Conditions;
using Project.Model.Dtos;

namespace Project.IBLL
{
    public interface IOperationLogService
    {
        /// <summary>
        /// 新增OperationLog
        /// </summary>
        /// <param name="entity"></param>
        /// <returns></returns>
        int Insert(OperationLog entity);

        /// <summary>
        ///     批量新增OperationLog
        /// </summary>
        /// <param name="entitys"></param>
        /// <returns></returns>
        bool Insert(List<OperationLog> entitys);

        /// <summary>
        /// 更新产品
        /// </summary>
        /// <returns></returns>
        bool Update(OperationLog entity);

        /// <summary>
        /// 批量更新(不使用事务)
        /// </summary>
        /// <param name="entitys"></param>
        /// <returns></returns>
        bool Update(List<OperationLog> entitys);

        /// <summary>
        /// 逻辑删除OperationLog
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        bool SoftDelete(int id);

        /// <summary>
        /// 批量逻辑删除OperationLog(不使用事务)
        /// </summary>
        /// <param name="ids"></param>
        /// <returns></returns>
        bool SoftDelete(List<int> ids);

        /// <summary>
        /// 判断OperationLog是否存在
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        bool Exists(int id);

        /// <summary>
        ///     根据主键获取OperationLog
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        OperationLog GetByPk(int id);

        /// <summary>
        ///     根据主键获取OperationLog集合
        /// </summary>
        /// <param name="ids"></param>
        /// <returns></returns>
        List<OperationLog> GetList(List<int> ids);

        /// <summary>
        ///     分页方法
        /// </summary>
        /// <param name="page"></param>
        /// <param name="size"></param>
        /// <param name="sort"></param>
        /// <param name="condition"></param>
        /// <returns></returns>
        PageModel<OperationLog> GetByPage(int page, int size, string sort, OperationLogCondition condition);
    }
}
