//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     生成时间 05/23/2019 10:37:27 By 朱峰
//     对此文件的更改可能会导致不正确的行为，并且如果
//     文件已存在，不会覆盖。
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Project.Model.Dtos
{
    public class AchievementDto
    {
        /// <summary>
        /// Desc_New:自增主键
        /// Default_New:
        /// Nullable_New:False
        /// </summary>           
        public int Id { get; set; }


        /// <summary>
        /// Desc_New:
        /// Default_New:
        /// Nullable_New:False
        /// </summary>           
        public int UserId { get; set; }


        /// <summary>
        /// Desc_New:
        /// Default_New:
        /// Nullable_New:False
        /// </summary>           
        public int AchievementNum { get; set; }


        /// <summary>
        /// Desc_New:
        /// Default_New:
        /// Nullable_New:False
        /// </summary>           
        public int AchievementType { get; set; }


        /// <summary>
        /// Desc_New:
        /// Default_New:
        /// Nullable_New:True
        /// </summary>           
        public string Remark { get; set; }

        /// <summary>
        ///     添加人
        /// </summary>
        public int AddUser { get; set; }

        /// <summary>
        ///     添加时间
        /// </summary>
        public DateTime AddTime { get; set; }

        /// <summary>
        ///     修改人
        /// </summary>
        public int UpdateUser { get; set; }

        /// <summary>
        ///     修改时间
        /// </summary>
        public DateTime UpdateTime { get; set; }

        public bool Marks { get; set; }
    }
}
