//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     生成时间 05/27/2019 13:55:17 By 朱峰
//     对此文件的更改可能会导致不正确的行为，并且如果
//     文件已存在，不会覆盖。
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Project.Model.Dtos
{
    public class AppointmentDto
    {
        /// <summary>
        /// Desc_New:自增主键
        /// Default_New:
        /// Nullable_New:False
        /// </summary>           
        public int Id { get; set; }


        /// <summary>
        /// Desc_New:预约日期
        /// Default_New:
        /// Nullable_New:False
        /// </summary>           
        public DateTime AppointmentDate { get; set; }


        /// <summary>
        /// Desc_New:预约时间ID
        /// Default_New:
        /// Nullable_New:True
        /// </summary>           
        public int? AppointmentTimeId { get; set; }


        /// <summary>
        /// Desc_New:预约时间名称
        /// Default_New:
        /// Nullable_New:True
        /// </summary>           
        public string AppointmentTimeName { get; set; }


        /// <summary>
        /// Desc_New:预约客户姓名
        /// Default_New:
        /// Nullable_New:True
        /// </summary>           
        public string AppointmentCustomerName { get; set; }


        /// <summary>
        /// Desc_New:预约项目ID
        /// Default_New:
        /// Nullable_New:True
        /// </summary>           
        public int? AppointmentProjectId { get; set; }


        /// <summary>
        /// Desc_New:预约项目名称
        /// Default_New:
        /// Nullable_New:True
        /// </summary>           
        public string AppointmentProjectName { get; set; }


        /// <summary>
        /// Desc_New:备注
        /// Default_New:
        /// Nullable_New:True
        /// </summary>           
        public string Remarks { get; set; }
    }
}
