//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     生成时间 05/06/2019 13:27:04 By 朱峰
//     对此文件的更改可能会导致不正确的行为，并且如果
//     文件已存在，不会覆盖。
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Project.Model.Dtos
{
    public class FtpConfigDto
    {
        /// <summary>
        /// Desc_New:自增主键
        /// Default_New:
        /// Nullable_New:False
        /// </summary>           
        public int Id { get; set; }


        /// <summary>
        /// Desc_New:名称
        /// Default_New:
        /// Nullable_New:False
        /// </summary>           
        public string Name { get; set; }


        /// <summary>
        /// Desc_New:账户
        /// Default_New:
        /// Nullable_New:False
        /// </summary>           
        public string Account { get; set; }


        /// <summary>
        /// Desc_New:密码
        /// Default_New:
        /// Nullable_New:False
        /// </summary>           
        public string Password { get; set; }


        /// <summary>
        /// Desc_New:地址
        /// Default_New:
        /// Nullable_New:False
        /// </summary>           
        public string Address { get; set; }


        /// <summary>
        /// Desc_New:端口
        /// Default_New:0
        /// Nullable_New:False
        /// </summary>           
        public int Port { get; set; }

        /// <summary>
        ///     添加时间
        /// </summary>
        public DateTime AddTime { get; set; }
    }
}
