//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     生成时间 04/25/2019 17:08:32 By 朱峰
//     对此文件的更改可能会导致不正确的行为，并且如果
//     文件已存在，不会覆盖。
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Project.Model.Dtos
{
    public class WordDto
    {

        /// <summary>
        /// Desc_New:自增主键
        /// Default_New:
        /// Nullable_New:False
        /// </summary>           
        public int Id { get; set; }


        /// <summary>
        /// Desc_New:
        /// Default_New:0
        /// Nullable_New:False
        /// </summary>           
        public int Type { get; set; }


        /// <summary>
        /// Desc_New:文档名
        /// Default_New:
        /// Nullable_New:False
        /// </summary>           
        public string Name { get; set; }

        /// <summary>
        /// Desc_New:文档路径
        /// Default_New:
        /// Nullable_New:False
        /// </summary>           
        public string RemotePath { get; set; }

        /// <summary>
        /// Desc_New:文档路径
        /// Default_New:
        /// Nullable_New:False
        /// </summary>           
        public string LocalPath { get; set; }


        /// <summary>
        /// Desc_New:日期
        /// Default_New:
        /// Nullable_New:False
        /// </summary>           
        public DateTime Date { get; set; }


        /// <summary>
        /// Desc_New:状态
        /// Default_New:0
        /// Nullable_New:False
        /// </summary>           
        public int Status { get; set; }

        public string StatusDesc { get; set; }

        /// <summary>
        ///     添加时间
        /// </summary>
        public DateTime AddTime { get; set; }
    }
}
