//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     生成时间 05/06/2019 13:27:04 By 朱峰
//     对此文件的更改可能会导致不正确的行为，并且如果
//     文件已存在，不会覆盖。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Project.IBLL;
using Project.IDAL;
using Project.Model;
using Project.Model.Conditions;
using Project.Model.Dtos;

namespace Project.BLL
{
    public class EmailConfigService : IEmailConfigService
    {
        private readonly IUnitOfWork _unitOfWork;

        public EmailConfigService(IEmailConfigManage emailConfigManage, IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        /// <summary>
        ///     新增EmailConfig
        /// </summary>
        /// <param name="entity"></param>
        /// <returns></returns>
        public int Insert(EmailConfig entity)
        {
            return _unitOfWork.EmailConfigManage.Insert(entity);
        }

        /// <summary>
        ///     批量新增EmailConfig
        /// </summary>
        /// <param name="entitys"></param>
        /// <returns></returns>
        public bool Insert(List<EmailConfig> entitys)
        {
            return _unitOfWork.EmailConfigManage.InsertWithNoTran(entitys);
        }

        /// <summary>
        ///     更新EmailConfig
        /// </summary>
        /// <returns></returns>
        public bool Update(EmailConfig entity)
        {
            return _unitOfWork.EmailConfigManage.Update(entity);
        }

        /// <summary>
        ///     批量更新(不使用事务)
        /// </summary>
        /// <param name="entitys"></param>
        /// <returns></returns>
        public bool Update(List<EmailConfig> entitys)
        {
            return _unitOfWork.EmailConfigManage.UpdateWithNoTran(entitys);
        }

        /// <summary>
        ///     逻辑删除EmailConfig
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public bool SoftDelete(int id)
        {
            return _unitOfWork.EmailConfigManage.SoftDelete(id);
        }

        /// <summary>
        ///     批量逻辑删除EmailConfig(不使用事务)
        /// </summary>
        /// <param name="ids"></param>
        /// <returns></returns>
        public bool SoftDelete(List<int> ids)
        {
            return _unitOfWork.EmailConfigManage.SoftDeleteWithNoTran(ids);
        }

        /// <summary>
        ///     判断EmailConfig是否存在
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public bool Exists(int id)
        {
            return _unitOfWork.EmailConfigManage.Exists(id);
        }

        /// <summary>
        ///     根据主键获取实体
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public EmailConfig GetByPk(int id)
        {
            return _unitOfWork.EmailConfigManage.GetByPk(id);
        }

        /// <summary>
        ///     根据主键获取实体集合
        /// </summary>
        /// <param name="ids"></param>
        /// <returns></returns>
        public List<EmailConfig> GetList(List<int> ids)
        {
            return _unitOfWork.EmailConfigManage.GetList(ids);
        }

        /// <summary>
        ///     分页方法
        /// </summary>
        /// <param name="page"></param>
        /// <param name="size"></param>
        /// <param name="sort"></param>
        /// <param name="condition"></param>
        /// <returns></returns>
        public PageModel<EmailConfig> GetByPage(int page, int size, string sort, EmailConfigCondition condition)
        {
            var dbCondition = new List<DbCondition<EmailConfig>>
            {
                new DbCondition<EmailConfig>
                {
                    IsWhere = !string.IsNullOrEmpty(condition.Keyword),
                    Expression = o=>o.Name.Contains(condition.Keyword)
                }
            };
            return _unitOfWork.EmailConfigManage.GetByPage(page, size, sort, dbCondition);
        }
    }
}
