//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     生成时间 07/24/2018 16:31:02 By 朱峰
//     对此文件的更改可能会导致不正确的行为，并且如果
//     文件已存在，不会覆盖。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Project.IBLL;
using Project.IDAL;
using Project.Model;
using Project.Model.Conditions;
using Project.Model.Dtos;

namespace Project.BLL
{
    public class OperationLogService : IOperationLogService
    {
        private readonly IUnitOfWork _unitOfWork;

        public OperationLogService(IOperationLogManage operationLogManage, IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        /// <summary>
        ///     新增OperationLog
        /// </summary>
        /// <param name="entity"></param>
        /// <returns></returns>
        public int Insert(OperationLog entity)
        {
            return _unitOfWork.OperationLogManage.Insert(entity);
        }

        /// <summary>
        ///     批量新增OperationLog
        /// </summary>
        /// <param name="entitys"></param>
        /// <returns></returns>
        public bool Insert(List<OperationLog> entitys)
        {
            return _unitOfWork.OperationLogManage.InsertWithNoTran(entitys);
        }

        /// <summary>
        ///     更新OperationLog
        /// </summary>
        /// <returns></returns>
        public bool Update(OperationLog entity)
        {
            return _unitOfWork.OperationLogManage.Update(entity);
        }

        /// <summary>
        ///     批量更新(不使用事务)
        /// </summary>
        /// <param name="entitys"></param>
        /// <returns></returns>
        public bool Update(List<OperationLog> entitys)
        {
            return _unitOfWork.OperationLogManage.UpdateWithNoTran(entitys);
        }

        /// <summary>
        ///     逻辑删除OperationLog
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public bool SoftDelete(int id)
        {
            return _unitOfWork.OperationLogManage.SoftDelete(id);
        }

        /// <summary>
        ///     批量逻辑删除OperationLog(不使用事务)
        /// </summary>
        /// <param name="ids"></param>
        /// <returns></returns>
        public bool SoftDelete(List<int> ids)
        {
            return _unitOfWork.OperationLogManage.SoftDeleteWithNoTran(ids);
        }

        /// <summary>
        ///     判断OperationLog是否存在
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public bool Exists(int id)
        {
            return _unitOfWork.OperationLogManage.Exists(id);
        }

        /// <summary>
        ///     根据主键获取实体
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public OperationLog GetByPk(int id)
        {
            return _unitOfWork.OperationLogManage.GetByPk(id);
        }

        /// <summary>
        ///     根据主键获取实体集合
        /// </summary>
        /// <param name="ids"></param>
        /// <returns></returns>
        public List<OperationLog> GetList(List<int> ids)
        {
            return _unitOfWork.OperationLogManage.GetList(ids);
        }

        /// <summary>
        ///     分页方法
        /// </summary>
        /// <param name="page"></param>
        /// <param name="size"></param>
        /// <param name="sort"></param>
        /// <param name="condition"></param>
        /// <returns></returns>
        public PageModel<OperationLog> GetByPage(int page, int size, string sort, OperationLogCondition condition)
        {
            var dbCondition = new List<DbCondition<OperationLog>>() {
                new DbCondition<OperationLog>{
                    IsWhere = !string.IsNullOrWhiteSpace(condition.Keyword),
                    Expression = o=>o.AddUserAccount.Contains(condition.Keyword)|| o.LogInfo.Contains(condition.Keyword)
                },
                new DbCondition<OperationLog>{
                    IsWhere = condition.LogType>0,
                    Expression = o=>o.Type == condition.LogType
                }
            };
            return _unitOfWork.OperationLogManage.GetByPage(page, size, sort, dbCondition);
        }
    }
}
