//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     生成时间 03/21/2019 08:57:52 By 朱峰
//     对此文件的更改可能会导致不正确的行为，并且如果
//     文件已存在，不会覆盖。
// </auto-generated>
//------------------------------------------------------------------------------
using Project.Model;

namespace Project.IDAL
{
    public interface IAccountManage : IManageBase<Account>
    {
        /// <summary>
        /// 判断LoginName是否存在
        /// </summary>
        /// <param name="loginName"></param>
        /// <param name="id"></param>
        /// <returns></returns>
        bool ExistLoginName(string loginName, int? id);

        /// <summary>
        /// 根据loginName和password获取账号
        /// </summary>
        /// <param name="loginName"></param>
        /// <param name="password"></param>
        /// <param name="id"></param>
        /// <returns></returns>
        Account GetAccount(string loginName, string password);
    }
}

