//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     生成时间 05/23/2019 10:49:13 By 朱峰
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.IDAL
{
    public interface IUnitOfWork
    {

        IAccountManage AccountManage { get; set; }

        IWordManage WordManage { get; set; }

        ITxtManage TxtManage { get; set; }

        IEmailConfigManage EmailConfigManage { get; set; }

        IFtpConfigManage FtpConfigManage { get; set; }

        IAchievementManage AchievementManage { get; set; }
    }
}
