//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     生成时间 05/23/2019 10:49:13 By 朱峰
//     对此文件的更改可能会导致不正确的行为，并且如果
//     文件已存在，不会覆盖。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Project.Core.Utility;
using Project.IBLL;
using Project.Model;
using Project.Model.Conditions;
using Project.Model.Dtos;
using Project.WebApi.Filters;
using Microsoft.AspNetCore.Cors;

namespace Project.WebApi.Controllers
{
    [Produces("application/json")]
    [Route("api/achievement")]
    [EnableCors("any")]
    public class AchievementController : Controller
    {
        private readonly IAchievementService _achievementService;

        public AchievementController(IAchievementService achievementService)
        {
            _achievementService = achievementService;
        }

        /// <summary>
        ///     根据id获取
        /// </summary>
        /// <param name="id">主键</param>
        /// <returns></returns>
        [HttpGet("{id}")]
        public IActionResult GetByPk(int id)
        {
            var model = _achievementService.GetByPk(id);
            return Ok(Mapper.Map<AchievementDto>(model));
        }

        /// <summary>
        ///     添加Achievement
        /// </summary>
        /// <param name="achievementDto">实体</param>
        /// <returns></returns>
        [HttpPost("")]
        [Validate]
        public IActionResult Insert([FromBody] AchievementDto achievementDto)
        {
            var achievement = Mapper.Map<Achievement>(achievementDto);
            return Ok(_achievementService.Insert(achievement));
        }

        /// <summary>
        ///     更新Achievement
        /// </summary>
        /// <param name="id">主键</param>
        /// <param name="achievementDto">实体</param>
        /// <returns></returns>
        [HttpPut("{id}")]
        [Validate]
        public IActionResult Update(int id, [FromBody] AchievementDto achievementDto)
        {
            var model = Mapper.Map<Achievement>(achievementDto);
            var result = _achievementService.Update(model);
            return Ok();
        }

        /// <summary>
        ///     逻辑删除achievement
        /// </summary>
        /// <param name="id">主键Id</param>
        /// <returns></returns>
        [HttpDelete("{id}")]
        public IActionResult Delete(int id)
        {
            var result = _achievementService.SoftDelete(id);
            return Ok();
        }

        /// <summary>
        /// 分页查询
        /// </summary>
        /// <param name="pi"></param>
        /// <param name="ps"></param>
        /// <param name="condition"></param>
        [HttpGet("get_by_page")]
        public IActionResult GetByPage(int pi, int ps, AchievementCondition condition = null)
        {
            var result = _achievementService.GetByPage(pi, ps, null, condition);
            return Ok(new
            {
                Total = result.Total,
                List = Mapper.Map<List<AchievementDto>>(result.Data)
            });
        }
    }
}
