//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     生成时间 04/26/2019 11:31:35 By 朱峰
//     对此文件的更改可能会导致不正确的行为，并且如果
//     文件已存在，不会覆盖。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Project.Core.Utility;
using Project.IBLL;
using Project.Model;
using Project.Model.Conditions;
using Project.Model.Dtos;
using Project.WebApi.Filters;
using Microsoft.AspNetCore.Cors;

namespace Project.WebApi.Controllers
{
    [Produces("application/json")]
    [Route("api/txt")]
    [EnableCors("any")]
    public class TxtController : Controller
    {
        private readonly ITxtService _txtService;

        public TxtController(ITxtService txtService)
        {
            _txtService = txtService;
        }

        /// <summary>
        ///     根据id获取
        /// </summary>
        /// <param name="id">主键</param>
        /// <returns></returns>
        [HttpGet("{id}")]
        public IActionResult GetByPk(int id)
        {
            var model = _txtService.GetByPk(id);
            return Ok(Mapper.Map<TxtDto>(model));
        }

        /// <summary>
        ///     添加Txt
        /// </summary>
        /// <param name="txtDto">实体</param>
        /// <returns></returns>
        [HttpPost("")]
        [Validate]
        public IActionResult Insert([FromBody] TxtDto txtDto)
        {
            var txt = Mapper.Map<Txt>(txtDto);
            return Ok(_txtService.Insert(txt));
        }

        /// <summary>
        ///     更新Txt
        /// </summary>
        /// <param name="id">主键</param>
        /// <param name="txtDto">实体</param>
        /// <returns></returns>
        [HttpPut("{id}")]
        [Validate]
        public IActionResult Update(int id, [FromBody] TxtDto txtDto)
        {
            var model = Mapper.Map<Txt>(txtDto);
            var result = _txtService.Update(model);
            return Ok();
        }

        /// <summary>
        ///     逻辑删除txt
        /// </summary>
        /// <param name="id">主键Id</param>
        /// <returns></returns>
        [HttpDelete("{id}")]
        public IActionResult Delete(int id)
        {
            var result = _txtService.SoftDelete(id);
            return Ok();
        }

        /// <summary>
        /// 分页查询
        /// </summary>
        /// <param name="pi"></param>
        /// <param name="ps"></param>
        /// <param name="condition"></param>
        [HttpGet("get_by_page")]
        public IActionResult GetByPage(int pi, int ps, TxtCondition condition = null)
        {
            var result = _txtService.GetByPage(pi, ps, null, condition);
            return Ok(new
            {
                Total = result.Total,
                List = Mapper.Map<List<TxtDto>>(result.Data)
            });
        }
    }
}
