//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     生成时间 05/23/2019 10:37:27 By 朱峰
//     对此文件的更改可能会导致不正确的行为，并且如果
//     文件已存在，不会覆盖。
// </auto-generated>
//------------------------------------------------------------------------------

using Project.IDAL;
using Project.Model;
using SqlSugar;

namespace Project.DAL
{
    public class AchievementManage : ManageBase<Achievement>,IAchievementManage
    {
		public AchievementManage()
		{
		}
	}
}
