//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     生成时间 04/26/2019 11:17:17 By 朱峰
//     对此文件的更改可能会导致不正确的行为，并且如果
//     文件已存在，不会覆盖。
// </auto-generated>
//------------------------------------------------------------------------------

using Project.IDAL;
using Project.Model;
using SqlSugar;

namespace Project.DAL
{
    public class TxtManage : ManageBase<Txt>,ITxtManage
    {
		public TxtManage()
		{
		}
	}
}
